# Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np


arr = np.zeros(10,dtype = int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


# 2. Create a vector with values ranging from 10 to 49.

In [2]:
array_1 = np.arange(10,50)

array_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
array_2 = np.arange(0,9).reshape(3,3)

print(array_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
n_array = np.array([1,2,0,0,4,0])

print("Original array:")
print(n_array)

# np.nonzero()
print("\nIndices of null elements:")

res = np.nonzero(n_array == 0)
print(res)


Original array:
[1 2 0 0 4 0]

Indices of null elements:
(array([2, 3, 5], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [12]:
import numpy as np

In [5]:
n_array = np.random.random((10,10))

print("the original array",n_array)

print("\n\n")
print("the minimum value of n_array: \n",n_array.min())
      
print("\n\n")
print("the maximun value of n_array: \n",n_array.max())


the original array [[0.69187456 0.79497298 0.36626079 0.04939706 0.89731403 0.94675224
  0.6600538  0.35444682 0.05997895 0.69626316]
 [0.23045643 0.5626402  0.66361342 0.24120733 0.17643295 0.04592889
  0.37200944 0.56090781 0.36599514 0.55318029]
 [0.79896784 0.39400522 0.75496313 0.79040531 0.3188288  0.89903556
  0.50026663 0.39130338 0.04929796 0.7559574 ]
 [0.84148592 0.27382335 0.48467187 0.88020048 0.34630547 0.40895718
  0.04150862 0.27298144 0.65143378 0.76723278]
 [0.54401984 0.73757851 0.29914279 0.47244487 0.8424853  0.85323553
  0.05848399 0.14127466 0.8413576  0.7632632 ]
 [0.62360586 0.74413327 0.17230043 0.39695283 0.8684596  0.77423627
  0.13602122 0.96183421 0.24572356 0.21908269]
 [0.40512497 0.75616004 0.22120323 0.02300394 0.25969849 0.16834357
  0.18780101 0.41973226 0.38300003 0.88310302]
 [0.64327913 0.40624592 0.28461919 0.89888001 0.69602423 0.88939193
  0.53956368 0.81828091 0.35855281 0.75388942]
 [0.92856044 0.65217502 0.69748862 0.66019329 0.08657697 0.73

# 6. Create a random vector of size 30 and find the mean value.

In [6]:
import numpy as np

z = np.random.random(30)
print("the random array is: \n",z)

mean_1 = z.mean()
print("\n\nthe mean value of array: \n ",mean_1)

the random array is: 
 [0.52799994 0.01532219 0.60085276 0.97943723 0.98885501 0.71445471
 0.54165155 0.25310158 0.58122574 0.73067107 0.16665505 0.36460486
 0.82654979 0.63521714 0.27529535 0.19902464 0.98118583 0.85519642
 0.44714895 0.61694428 0.50242864 0.98835996 0.81637378 0.02803744
 0.15185125 0.75731726 0.95961603 0.31600629 0.11612885 0.42644321]


the mean value of array: 
  0.5454652263565559
